---
- name: "Installing some stuff"
  hosts: all
  become: True

  pre_tasks:
    - name: "Installing dependencies"
      yum:
        name: "{{ item }}"
        state: installed
      with_items:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2

    - name: "Installing repo"
      shell: "{{ item }}"
      args:
        warn: False
      with_items:
        - yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
        - yum-config-manager --enable docker-ce-edge

    - name: "Installing docker"
      yum:
        name: docker-ce
        state: installed

    - name: "Enable docker"
      systemd:
        name: docker
        state: stopped
        enabled: True

  roles:
    - system
